### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by DavidOcea** [cool-RR/PySnooper#100]

**Comment by cool-RR** [comment]
```
Traceback (most recent call last):   File "/Users/yangdecheng/Downloads/test.py", line 15, in <module>     foo()   File "/Users/yangdecheng/Downloads/test.py", line 9, in foo     with pysnooper.snoop(): AttributeError: __enter__
```

**Comment by cool-RR** [comment]
@DavidOcea Please provide the full file

**Comment by alexmojaki** [comment]
@cool-RR I think you need to release the context manager stuff to pypi.

**Comment by cool-RR** [comment]
Right. @DavidOcea Please upgrade PySnooper and try again.

**Comment by DavidOcea** [comment]
i upgrade  pysnooper and the problem is solved, thank you .
