### ISSUE TITLE
pip install fails for missing requirements.txt

### ISSUE THREAD

**Issue by am-zed** [cool-RR/PySnooper#26]
PIP install fails with missing _requirements.txt_ file:

``` shell
$ pip install pysnooper
Collecting pysnooper
  Using cached https://files.pythonhosted.org/packages/43/58/e36822363b00e3a7f15621b5b34587e171521c55bc19970cb4754ba08d18/PySnooper-0.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-blixjg7f/pysnooper/setup.py", line 16, in <module>
        install_requires=open('requirements.txt', 'r').read().split('\n'),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-blixjg7f/pysnooper/
```

``` shell
$ wget https://files.pythonhosted.org/packages/43/58/e36822363b00e3a7f15621b5b34587e171521c55bc19970cb4754ba08d18/PySnooper-0.0.10.tar.gz
...

$ tar tf PySnooper-0.0.10.tar.gz
PySnooper-0.0.10/
PySnooper-0.0.10/PKG-INFO
PySnooper-0.0.10/PySnooper.egg-info/
PySnooper-0.0.10/PySnooper.egg-info/PKG-INFO
PySnooper-0.0.10/PySnooper.egg-info/SOURCES.txt
PySnooper-0.0.10/PySnooper.egg-info/dependency_links.txt
PySnooper-0.0.10/PySnooper.egg-info/requires.txt
PySnooper-0.0.10/PySnooper.egg-info/top_level.txt
PySnooper-0.0.10/README.md
PySnooper-0.0.10/pysnooper/
PySnooper-0.0.10/pysnooper/__init__.py
PySnooper-0.0.10/pysnooper/pycompat.py
PySnooper-0.0.10/pysnooper/pysnooper.py
PySnooper-0.0.10/pysnooper/tracer.py
PySnooper-0.0.10/pysnooper/utils.py
PySnooper-0.0.10/setup.cfg
PySnooper-0.0.10/setup.py
PySnooper-0.0.10/tests/
PySnooper-0.0.10/tests/__init__.py
PySnooper-0.0.10/tests/test_pysnooper.py
PySnooper-0.0.10/tests/utils.py
```

**Comment by cool-RR** [comment]
@bittner I've also seen it happen on my computer, but I couldn't replicate it. Do you have an opinion on why this problem happens and how to prevent it?

**Comment by am-zed** [comment]
You probably must check your pypi package and add the missing file.

A workaround is to use the github repo directly:

``` shell
$ git clone --depth 1 https://github.com/cool-RR/PySnooper
...

$ python setup.py install --user
...
```

**Comment by bittner** [comment]
Adding the `MANIFEST.in` file I mentioned in #22 will probably fix this problem. The content of the file should probably look like this:

```
include README.md requirements.in requirements.txt
```

For background reading see the [related Python documentation](https://docs.python.org/3.7/distutils/sourcedist.html#specifying-the-files-to-distribute).

**Comment by cool-RR** [comment]
Thanks Peter! I added a MANIFEST.in file now.

@am-zed If it happens again on >=0.0.11, please reopen this issue.
